[package]
name = 'Hello_World'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
hello = "25e6d86a5a7083d9d61e40381e5238ab6d2e785825eba0183cebb6009483dab4"